"""Edit decks and users models

Revision ID: 44e08db9c9ef
Revises: 7cec54e36d6f
Create Date: 2025-07-10 15:04:31.402328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44e08db9c9ef'
down_revision: Union[str, None] = '7cec54e36d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('category', sa.String(), nullable=False))
    op.drop_column('decks', 'theme')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2025-07-10 14:14:56.595222'::timestamp without time zone"),
               existing_nullable=False)
    op.add_column('decks', sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('decks', 'category')
    # ### end Alembic commands ###
