"""Card and deck edit

Revision ID: 5881c7b4b0bb
Revises: 5c01ca76ec90
Create Date: 2025-07-02 18:08:50.108931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5881c7b4b0bb'
down_revision: Union[str, None] = '5c01ca76ec90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('transcription', sa.String(), nullable=False))
    op.add_column('card', sa.Column('image_url', sa.String(), nullable=False))
    op.add_column('deck', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deck', 'image_url')
    op.drop_column('card', 'image_url')
    op.drop_column('card', 'transcription')
    # ### end Alembic commands ###
