"""Edit models relationships

Revision ID: e4c3ed57bd71
Revises: 551c590f9c03
Create Date: 2025-07-07 15:10:11.639487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4c3ed57bd71'
down_revision: Union[str, None] = '551c590f9c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='NOW()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2025-07-07 12:49:10.225231'::timestamp without time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
